### ISSUE TITLE
Correctors should be able to create students in TMS

### ISSUE THREAD

**Issue by NadineNKoch** [TMS-Uni-Stuttgart/Tutor-Management-System#1015]
# :ticket: Description
The correctors should be able to also create student in TMS.

**Comment by NadineNKoch** [comment]
That we employees do not have to do this. This reduces our workload and it is fairer if the correctors as the tutors create their students.

**Comment by Dudrie** [comment]
But employees should not do this in the first place. Tutors should create their students. Do you have tutorials without a designated tutor?

**Comment by NadineNKoch** [comment]
There are several tutorials that are lead by employees. The exercises from those groups are corrected by correctors. For the employees, it would be great to reduce the workload and enable their correctors to set up students in TMS.

**Comment by Dudrie** [comment]
Would setting the correctors as tutors be an option instead?

**Comment by Dudrie** [comment]
Alternative idea: If #1012 would be implemented in a way that tutors (not correctors) can import CSV files the correctors could be tasked to create such a CSV file. This CSV file can imported by the actual tutor afterwards. This would keep the role restrictions as is and correctors would not be able to access more information than they need.

**Comment by nk-coding** [comment]
Setting the corrector as tutor does not seem to be an option at least to me, as it makes it impossible for the real tutor to edit/see necessary information.
Giving correctors the permission to edit student data also does not seem to be a good option, as it makes the corrector role basically pointless (if tutors and correctors can do the same, why having the distinction in the first place).
For now, the csv import seems to be a good option, as it allows corrector to do the majority of the work, however keeps this information private in general.
For the future, maybe allowing multiple tutors may be an option, in the case the corrector should also do tutor-exclusive stuff

**Comment by nk-coding** [comment]
Decision: we want the "multiple tutors" feature
