### ISSUE TITLE
Remove duplicated selection choices

### ISSUE THREAD

**Issue by delvh** [TMS-Uni-Stuttgart/Tutor-Management-System#1021]
# ⚡ Actual behaviour 
![image](https://user-images.githubusercontent.com/51889757/198719931-32d05d86-dbb6-4c08-9af7-cac945054dde.png)
The same behavior is present in the sidebar menu item for `Scheinklausuren` 

# :heavy_check_mark: Expected behaviour
One of the two duplicated options should not be present, especially as they seem to map to the exact same action/ item, since both are highlighted as active.

# :joystick: Steps to reproduce
1. Be a tutor and corrector (with more than tutorium?) 
2. Enjoy

**Comment by Dudrie** [comment]
Why are you assigned as tutor *and* corrector in the first place? A tutor can do everything a corrector can do aswell. The corrector of a tutorial is a person who corrects the hand ins if (and only if) this the tutor is not the one who does the corrections.

Therefore, a tutor should not be corrector of the same tutorial. Maybe one should add this as a validation rule for creating/updating tutorials, etc.

**Comment by qwach** [comment]
Looks like that for me too

**Comment by nk-coding** [comment]
TODO: check if these are different views (if not wontfix, otherwise simple frontend fix)
