### ISSUE TITLE
Auto-completion for tutor search

### ISSUE THREAD

**Issue by marfraTUC** [TMS-Uni-Stuttgart/Tutor-Management-System#43]
# :mag_right: Short
Auto-compleation for tutor search

# :ticket: Description
Currently if you want to add a tutor to a tutorium you need to search a rather long list. It would be better to have a textfield which does auto completion. Only in the case that you do not know the name you should be able to click a search icon which opens the full list.

**Comment by Dudrie** [comment]
This is in fact planed for other textfields aswell. However, integrating a proper auto-complete with the current custom form component for React is not trivial.

**Comment by Dudrie** [comment]
Quick update: This will be worked on as soon as the new [Autocomplete](https://material-ui.com/components/autocomplete/) component is ready for production (ie leaves the lab).
