### ISSUE TITLE
Share tutorial (ie allow more than one tutor per tutorial)

### ISSUE THREAD

**Issue by Dudrie** [TMS-Uni-Stuttgart/Tutor-Management-System#791]
# :ticket: Description

As tutorials moved to online courses some may be shared by two tutors (or more). However each one only has access to his/her students right now. 

The idea is to implement an option that allows a tutorial to be shared between tutors. "Sharing" means that more than one tutor can be assigned to it and both tutors have full access to the tutorial (as one single tutor has right now).

**Comment by nk-coding** [comment]
See #1015
